---
- hosts: webservers 
  become: True
  tasks:
    - name: create file
      copy:
        src: simple-http
        dest: /var/www/html/
        mode: '0111'
    - name: stop service
      service:
        name: 'simple-http'
        state: stopped
    - name: start service
      service:
        name: 'simple-http'
        state: start
    
